name: Linux (OpenGL)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Apt Update
      run: sudo apt update
    - name: Apt Install
      run: sudo apt-get install libasound2-dev libxinerama-dev libxrandr-dev libgl1-mesa-dev libxi-dev libxcursor-dev libudev-dev libwayland-dev wayland-protocols libxkbcommon-dev ninja-build --yes --quiet
    - name: Get ImageMagick and xvfb
      run: sudo apt install imagemagick xvfb
    - name: Get Submodules
      run: ./get_dlc
    - name: Temporary OpenGL scissor patch
      run: git -C krink/Kinc apply openglscissor.patch
    - name: Compile
      run: ./krink/Kinc/make -g opengl --compile
    - name: Run Test 1
      working-directory: ./tests/bin
      run: xvfb-run ./krass
    - name: Check Test 1
      run: compare-im6 -verbose -metric mae tests/compare/basic.png tests/bin/basic.png difference.png
